update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    run_tests(workspace: "SNM.xcworkspace",
      devices: ["iPhone X", "iPad (5th generation)"],
      scheme: "SNM",
      code_coverage: true)
    codecov_reporter(
      token: ENV["CODECOV_TOKEN"]
    )
  end
end
