update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    setup_travis
  end

  desc "unit tests"
  lane :tests do
    run_tests(workspace: "SNM.xcworkspace",
      clean: true,
      reinstall_app: true,
      app_identifier: "SNM",
      devices: ["iPhone X", "iPad (5th generation)"],
      scheme: "SNM",
      code_coverage: true)
    codecov_reporter(
      token: ENV["CODECOV_TOKEN"]
    )
  end
end
