name: GithubActions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fastlane Action
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: maierj/fastlane-action@v1.4.0
      with: 
       lane: tests
    # - name: Upload coverage to Codecov  
    #   uses: codecov/codecov-action@v1
    #   with:
    #     flags: unittests
    #     fail_ci_if_error: true
